version: "3.11"

volumes:
  redis:

services:
  cache:
    image: redis/redis-stack-server:latest
    restart: always
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - 6379:6379
    volumes:
      - redis:/data
    environment:
      REDIS_ARGS: "--appendonly yes --aof-use-rdb-preamble yes"

  api:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn main:app --workers 1 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000
    expose:
      - 8000
    environment:
      - PORT=8000
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    ports:
      - 8000:8000
    depends_on:
      - cache

  web:
    restart: always
    build: nginx
    ports:
      - 80:80
    depends_on:
      - api
