version: "3.11"

volumes:
  redis:

services:
  redis:
    image: "redis/redis-stack-server:latest"
    restart: always
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_DB=${REDIS_DB}
    volumes:
      - redis:/data

  research-gpt:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - 8000
    environment:
      - MODULE_NAME=main
      - VARIABLE_NAME=app
    volumes:
      - .:/app
    depends_on:
      - redis

  nginx:
    image: nginx:latest
    restart: unless-stopped
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    depends_on:
      - research-gpt

networks:
  default:
    external:
      name: nginx_network
