version: "3.11"

volumes:
  redis:

services:
  cache:
    image: redis/redis-stack-server:latest
    restart: always
    environment:
      - REDIS_ARGS=--requirepass ${REDIS_PASSWORD} --maxmemory 100mb --maxmemory-policy allkeys-lru --appendonly yes
    volumes:
      - redis:/data

  api:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn main:app --workers 1 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000
    expose:
      - 8000
    environment:
      - PORT=8000
    ports:
      - 8000:8000
    depends_on:
      - cache

  web:
    restart: always
    build: nginx
    ports:
      - 80:80
    depends_on:
      - api
