version: "3.11"

volumes:
  redis:

services:
  redis:
    image: "redis/redis-stack-server:latest"
    restart: always
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_DB=${REDIS_DB}
    volumes:
      - redis:/data

  api:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - 8000
    environment:
      - PORT=8000
    ports:
      - 8000:8000
    depends_on:
      - redis

  web:
    build: nginx
    ports:
      - 80:80
    depends_on:
      - api
