version: "3.11"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - 8000
    environment:
      - PORT=8000
    ports:
      - 8000:8000

  web:
    build: nginx
    ports:
      - 80:80
    depends_on:
      - api
