version: "3.11"

networks:
  research-gpt:

volumes:
  redis:

services:
  cache:
    image: redis/redis-stack-server:latest
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redis:/data
    environment:
      REDIS_ARGS: "--allow-empty-password yes --maxmemory 256mb --maxmemory-policy allkeys-lru --appendonly yes"
    networks:
      - research-gpt

  api:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn main:app --workers 1 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000
    expose:
      - 8000
    environment:
      - PORT=8000
      - REDIS_HOST=cache
      - REDIS_PORT=6379
    ports:
      - 8000:8000
    depends_on:
      - cache
    networks:
      - research-gpt

  web:
    restart: always
    build: nginx
    ports:
      - 80:80
    depends_on:
      - api
    networks:
      - research-gpt
