version: "3.11"

services:
  api:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn main:app --workers 1 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000
    expose:
      - 8000
    environment:
      - PORT=8000
    ports:
      - 8000:8000

  web:
    restart: always
    build: nginx
    ports:
      - 80:80
    depends_on:
      - api
