version: "3.11"

volumes:
  redis:

services:
  redis:
    image: "redis/redis-stack-server:latest"
    restart: always
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD
      - REDIS_DB
    volumes:
      - redis:/data

  research-gpt:
    build: .
    volumes:
      - .:/server
    ports:
      - "8000:8000"
    depends_on:
      - redis
    env_file:
      - config/.env

  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - research-gpt
